### ISSUE TITLE
Exclude pages/posts/or page template

### ISSUE THREAD

**Issue by JacobLett** [kevinweber/wbounce#6]
Is there a way to exclude pages from firing the modal? Thanks for sharing this plugin it works well.

**Comment by kevinweber** [comment]
Hi Jacob,
yes, you can find a meta box next to every post/page editor
![screenshot-4](https://cloud.githubusercontent.com/assets/2785791/9359831/3fde5a62-4693-11e5-9969-1062246d0407.png)

And you can define a default template type on the admin panel.
However, there's no extra option to exclude the popup from just the home page or just the archives.

– Kevin

**Comment by JacobLett** [comment]
Perfect. Thank you Kevin. One more question.

Is it possible to have it disabled globally and then selectively turn it on? Or do you have to have it on globally and then selectively turn it off?

**Comment by kevinweber** [comment]
Yes, you can turn it off globally on the admin panel and then selectively override that setting (thus, turn it on).

**Comment by JacobLett** [comment]
Thank you Kevin.
