### ISSUE TITLE
Fire only after first page load

### ISSUE THREAD

**Issue by FiberMan** [kevinweber/wbounce#8]
Hi guys,
Is it possible to add such functionality: to fire the message only if user wants to exit right after he came to the site? I mean - after only one page load per session.
For example, to add to the Options "Count of visited pages after which massage will be fired".

I have "Bounce rate" on my site around 80% and I would like to ask people why do they leave the site right after they came.

**Comment by kevinweber** [comment]
Hi @FiberMan,
this is a nice idea. However, right now, I don't plan to implement more features. You can request that feature on the [Ouibounce project](https://github.com/carlsednaoui/ouibounce/issues) on which this plugin bases. When Ouibounce has that feature, I will also integrate it into the WordPress plugin.
